apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "yarowa.fullname" . }}-ingress
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: casestudy.local.yarowa.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "yarowa.fullname" . }}-service
              port:
                number: 80
